<?php
/**
 * Seed: 12 servicios clínicos.
 *
 * @package PerritoFeliz
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

function perrito_seed_servicios() {
	$servicios = array(
		array(
			'slug'  => 'consulta-general',
			'title' => 'Consulta veterinaria general',
			'excerpt' => 'Atención médica para controles, evaluación de síntomas, seguimiento de enfermedades, orientación preventiva y revisión integral de perros y gatos.',
			'content' => "<p>Nuestra consulta general es la puerta de entrada al cuidado integral de tu mascota. Evaluamos signos vitales, estado físico, nutrición, comportamiento y antecedentes clínicos para entregarte un plan claro de seguimiento.</p>\n<p>Trabajamos con fichas digitales, historial clínico completo y protocolos de atención que aseguran continuidad del cuidado.</p>",
			'cat'   => 'preventivo',
			'order' => 1,
			'fields' => array(
				'precio_desde'     => 22000,
				'duracion_estimada' => '30 a 45 minutos',
				'es_urgencia'      => false,
				'icono_slug'       => 'service-consulta',
				'ilustracion_slug' => 'hero-home',
				'cta_texto'        => 'Agendar consulta',
				'incluye' => array(
					array( 'item' => 'Anamnesis completa' ),
					array( 'item' => 'Examen físico general' ),
					array( 'item' => 'Revisión de signos vitales' ),
					array( 'item' => 'Evaluación de peso y condición corporal' ),
					array( 'item' => 'Plan terapéutico u orden de exámenes' ),
					array( 'item' => 'Indicación de seguimiento' ),
				),
				'casos_frecuentes' => array(
					array( 'item' => 'Chequeos de rutina' ),
					array( 'item' => 'Vacunación y desparasitación' ),
					array( 'item' => 'Pérdida de apetito' ),
					array( 'item' => 'Cambios de comportamiento' ),
				),
			),
		),
		array(
			'slug'  => 'urgencias-24-7',
			'title' => 'Urgencias veterinarias 24/7',
			'excerpt' => 'Atención inmediata para situaciones que no pueden esperar. Triage rápido, estabilización y comunicación clara con el tutor desde el primer momento.',
			'content' => "<p>Nuestro servicio de urgencias funciona las 24 horas, los 7 días de la semana. Priorizamos estabilización, triage rápido y pruebas diagnósticas esenciales.</p>\n<p>Si tu mascota presenta una urgencia, llámanos antes de salir para que podamos prepararnos para recibirla.</p>",
			'cat'   => 'urgencia',
			'order' => 2,
			'fields' => array(
				'precio_desde'     => 0,
				'duracion_estimada' => 'Atención inmediata',
				'es_urgencia'      => true,
				'icono_slug'       => 'service-urgencia',
				'ilustracion_slug' => 'hero-urgencia',
				'cta_texto'        => 'Llamar ahora',
				'incluye' => array(
					array( 'item' => 'Triage inmediato' ),
					array( 'item' => 'Estabilización primaria' ),
					array( 'item' => 'Exámenes prioritarios' ),
					array( 'item' => 'Comunicación con tutor' ),
					array( 'item' => 'Derivación a hospitalización si es necesario' ),
				),
				'casos_frecuentes' => array(
					array( 'item' => 'Vómitos y diarrea severa' ),
					array( 'item' => 'Convulsiones' ),
					array( 'item' => 'Traumatismos y atropellos' ),
					array( 'item' => 'Intoxicaciones' ),
					array( 'item' => 'Dificultad respiratoria' ),
					array( 'item' => 'Hemorragias' ),
					array( 'item' => 'Obstrucciones urinarias' ),
				),
			),
		),
		array(
			'slug'  => 'ambulancia-veterinaria',
			'title' => 'Ambulancia veterinaria de emergencia',
			'excerpt' => 'Unidades móviles adaptadas para traslado asistido de pacientes en estado delicado o con movilidad reducida. Tiempo promedio de respuesta 25-50 minutos.',
			'content' => "<p>Contamos con unidades móviles adaptadas para traslado asistido de pacientes en estado delicado o con movilidad reducida. Cubrimos comunas del centro y oriente de Santiago con tiempos promedio de 25 a 50 minutos.</p>\n<p>Este servicio es ideal para mascotas que no pueden movilizarse por dolor o lesión, sospecha de golpe de calor, dificultad respiratoria, sangrado activo, pacientes geriátricos descompensados o postoperatorios complejos.</p>",
			'cat'   => 'urgencia',
			'order' => 3,
			'fields' => array(
				'precio_desde'     => 45000,
				'duracion_estimada' => '25-50 min de respuesta',
				'es_urgencia'      => true,
				'icono_slug'       => 'service-ambulancia',
				'ilustracion_slug' => 'hero-ambulancia',
				'cta_texto'        => 'Solicitar ambulancia',
				'incluye' => array(
					array( 'item' => 'Traslado veterinario asistido' ),
					array( 'item' => 'Evaluación inicial en domicilio' ),
					array( 'item' => 'Oxigenoterapia básica' ),
					array( 'item' => 'Estabilización inicial según caso' ),
					array( 'item' => 'Monitorización durante traslado' ),
					array( 'item' => 'Comunicación con clínica para recepción' ),
				),
				'casos_frecuentes' => array(
					array( 'item' => 'Mascotas que no pueden movilizarse' ),
					array( 'item' => 'Sospecha de golpe de calor' ),
					array( 'item' => 'Dificultad respiratoria' ),
					array( 'item' => 'Sangrado activo' ),
					array( 'item' => 'Pacientes geriátricos descompensados' ),
					array( 'item' => 'Postoperatorios complejos' ),
				),
			),
		),
		array(
			'slug'  => 'cirugia',
			'title' => 'Cirugía veterinaria',
			'excerpt' => 'Cirugías programadas y procedimientos de urgencia con evaluación preanestésica, monitorización intraoperatoria y protocolo analgésico completo.',
			'content' => "<p>Realizamos cirugías programadas y procedimientos quirúrgicos de complejidad media y alta. Contamos con pabellón equipado, evaluación preanestésica, monitorización intraoperatoria y protocolo analgésico personalizado.</p>\n<p>Cada cirugía incluye alta con instrucciones claras y seguimiento postoperatorio.</p>",
			'cat'   => 'quirurgico',
			'order' => 4,
			'fields' => array(
				'precio_desde'     => 85000,
				'duracion_estimada' => 'Según procedimiento',
				'es_urgencia'      => false,
				'icono_slug'       => 'service-cirugia',
				'ilustracion_slug' => 'hero-esterilizacion',
				'cta_texto'        => 'Cotizar cirugía',
				'incluye' => array(
					array( 'item' => 'Evaluación preanestésica' ),
					array( 'item' => 'Exámenes previos según caso' ),
					array( 'item' => 'Protocolo anestésico personalizado' ),
					array( 'item' => 'Monitorización intraoperatoria' ),
					array( 'item' => 'Protocolo analgésico' ),
					array( 'item' => 'Alta con instrucciones' ),
					array( 'item' => 'Seguimiento postoperatorio' ),
				),
				'casos_frecuentes' => array(
					array( 'item' => 'Esterilización y castración' ),
					array( 'item' => 'Extracción de masas' ),
					array( 'item' => 'Cirugía digestiva básica' ),
					array( 'item' => 'Sutura de heridas' ),
					array( 'item' => 'Cirugía dental' ),
					array( 'item' => 'Cirugía de tejidos blandos' ),
				),
			),
		),
		array(
			'slug'  => 'hospitalizacion',
			'title' => 'Hospitalización',
			'excerpt' => 'Áreas diferenciadas para observación, estabilización y hospitalización breve o prolongada con monitoreo constante y reportes al tutor.',
			'content' => "<p>Contamos con áreas diferenciadas para hospitalización canina y felina, monitoreo de signos vitales, manejo del dolor y protocolos de higiene y bioseguridad.</p>\n<p>Reportamos periódicamente al tutor sobre la evolución del paciente.</p>",
			'cat'   => 'urgencia',
			'order' => 5,
			'fields' => array(
				'precio_desde'     => 38000,
				'duracion_estimada' => 'Según caso clínico',
				'es_urgencia'      => false,
				'icono_slug'       => 'service-hospitalizacion',
				'ilustracion_slug' => 'hero-esterilizacion',
				'cta_texto'        => 'Más información',
				'incluye' => array(
					array( 'item' => 'Monitoreo de signos vitales' ),
					array( 'item' => 'Control de medicación' ),
					array( 'item' => 'Manejo del dolor' ),
					array( 'item' => 'Reportes periódicos al tutor' ),
					array( 'item' => 'Protocolos de higiene y bioseguridad' ),
				),
				'casos_frecuentes' => array(
					array( 'item' => 'Pacientes postquirúrgicos' ),
					array( 'item' => 'Deshidratación severa' ),
					array( 'item' => 'Trastornos gastrointestinales' ),
					array( 'item' => 'Enfermedades infecciosas' ),
					array( 'item' => 'Pacientes geriátricos descompensados' ),
				),
			),
		),
		array(
			'slug'  => 'diagnostico-examenes',
			'title' => 'Diagnóstico y exámenes',
			'excerpt' => 'Exámenes internos y coordinación con laboratorios externos. Hemograma, perfil bioquímico, radiografías, ecografías y más.',
			'content' => "<p>Ofrecemos exámenes internos y coordinación con laboratorios externos según la complejidad del caso. Los resultados se integran a la ficha clínica del paciente.</p>",
			'cat'   => 'diagnostico',
			'order' => 6,
			'fields' => array(
				'precio_desde'     => 15000,
				'duracion_estimada' => 'Entrega en 24-48h',
				'es_urgencia'      => false,
				'icono_slug'       => 'service-examenes',
				'ilustracion_slug' => 'hero-home',
				'cta_texto'        => 'Solicitar examen',
				'incluye' => array(
					array( 'item' => 'Hemograma' ),
					array( 'item' => 'Perfil bioquímico' ),
					array( 'item' => 'Coproparasitológico' ),
					array( 'item' => 'Uroanálisis' ),
					array( 'item' => 'Test rápidos' ),
					array( 'item' => 'Radiografías y ecografías' ),
					array( 'item' => 'Citologías' ),
					array( 'item' => 'Perfil prequirúrgico' ),
				),
				'casos_frecuentes' => array(),
			),
		),
		array(
			'slug'  => 'odontologia',
			'title' => 'Odontología veterinaria',
			'excerpt' => 'La salud bucal es una de las áreas más olvidadas y más importantes para el bienestar general. Limpiezas dentales, extracciones y tratamiento de gingivitis.',
			'content' => "<p>La salud bucal es fundamental para el bienestar general. Realizamos limpiezas dentales con ultrasonido, extracciones simples, tratamiento de gingivitis y educación preventiva.</p>",
			'cat'   => 'quirurgico',
			'order' => 7,
			'fields' => array(
				'precio_desde'     => 55000,
				'duracion_estimada' => '60-90 minutos',
				'es_urgencia'      => false,
				'icono_slug'       => 'service-odontologia',
				'ilustracion_slug' => 'hero-home',
				'cta_texto'        => 'Agendar limpieza',
				'incluye' => array(
					array( 'item' => 'Evaluación dental' ),
					array( 'item' => 'Limpieza dental con ultrasonido' ),
					array( 'item' => 'Extracciones simples' ),
					array( 'item' => 'Tratamiento de gingivitis' ),
					array( 'item' => 'Educación preventiva' ),
				),
				'casos_frecuentes' => array(),
			),
		),
		array(
			'slug'  => 'dermatologia',
			'title' => 'Dermatología y alergias',
			'excerpt' => 'Atención de casos de prurito, irritación, caída excesiva de pelo, otitis recurrente y sospecha de alergias alimentarias o ambientales.',
			'content' => "<p>Atendemos casos frecuentes de prurito, irritación, caída excesiva de pelo, otitis recurrente y sospecha de alergias. Diseñamos planes integrales con ajustes nutricionales y seguimiento de piel y manto.</p>",
			'cat'   => 'preventivo',
			'order' => 8,
			'fields' => array(
				'precio_desde'     => 28000,
				'duracion_estimada' => '45 minutos',
				'es_urgencia'      => false,
				'icono_slug'       => 'service-dermatologia',
				'ilustracion_slug' => 'hero-home',
				'cta_texto'        => 'Agendar consulta',
				'incluye' => array(
					array( 'item' => 'Evaluación dermatológica' ),
					array( 'item' => 'Rasurados diagnósticos' ),
					array( 'item' => 'Citologías cutáneas' ),
					array( 'item' => 'Plan de control de alergias' ),
					array( 'item' => 'Ajustes nutricionales' ),
				),
				'casos_frecuentes' => array(),
			),
		),
		array(
			'slug'  => 'nutricion-clinica',
			'title' => 'Nutrición clínica',
			'excerpt' => 'Planes nutricionales según edad, condición clínica y estilo de vida. Obesidad, alergias alimentarias, dietas renales y recuperación postoperatoria.',
			'content' => "<p>La alimentación correcta puede cambiar por completo la calidad de vida de una mascota. Diseñamos dietas terapéuticas según edad, raza, antecedentes médicos y objetivos.</p>",
			'cat'   => 'preventivo',
			'order' => 9,
			'fields' => array(
				'precio_desde'     => 22000,
				'duracion_estimada' => '45 minutos',
				'es_urgencia'      => false,
				'icono_slug'       => 'service-nutricion',
				'ilustracion_slug' => 'hero-cachorro',
				'cta_texto'        => 'Agendar nutrición',
				'incluye' => array(
					array( 'item' => 'Evaluación nutricional' ),
					array( 'item' => 'Plan alimenticio personalizado' ),
					array( 'item' => 'Seguimiento de peso' ),
					array( 'item' => 'Recomendación de productos' ),
				),
				'casos_frecuentes' => array(
					array( 'item' => 'Obesidad' ),
					array( 'item' => 'Alergias alimentarias' ),
					array( 'item' => 'Dietas digestivas' ),
					array( 'item' => 'Enfermedad renal' ),
					array( 'item' => 'Recuperación postoperatoria' ),
				),
			),
		),
		array(
			'slug'  => 'peluqueria-clinica',
			'title' => 'Peluquería y bienestar',
			'excerpt' => 'Área de baño y peluquería orientada a estética y salud dermatológica. Baño medicado, corte de pelo, deslanado y spa de hidratación.',
			'content' => "<p>Contamos con un área de baño y peluquería orientada tanto a estética como a salud dermatológica, coordinada con el equipo médico para pacientes sensibles.</p>",
			'cat'   => 'bienestar',
			'order' => 10,
			'fields' => array(
				'precio_desde'     => 18000,
				'duracion_estimada' => '60-90 minutos',
				'es_urgencia'      => false,
				'icono_slug'       => 'service-peluqueria',
				'ilustracion_slug' => 'hero-cachorro',
				'cta_texto'        => 'Agendar peluquería',
				'incluye' => array(
					array( 'item' => 'Baño medicado' ),
					array( 'item' => 'Corte de pelo' ),
					array( 'item' => 'Deslanado' ),
					array( 'item' => 'Corte de uñas' ),
					array( 'item' => 'Limpieza de oídos' ),
					array( 'item' => 'Higiene sanitaria' ),
				),
				'casos_frecuentes' => array(),
			),
		),
		array(
			'slug'  => 'visitas-a-domicilio',
			'title' => 'Consulta veterinaria a domicilio',
			'excerpt' => 'Ideal para mascotas ansiosas, pacientes geriátricos, tutores con dificultad de traslado o controles simples. Consultas, vacunación y más.',
			'content' => "<p>Las visitas a domicilio son una solución ideal para mascotas ansiosas, pacientes geriátricos o tutores con dificultad de traslado. Realizamos consultas generales, vacunación, controles postoperatorios y más.</p>",
			'cat'   => 'preventivo',
			'order' => 11,
			'fields' => array(
				'precio_desde'     => 42000,
				'duracion_estimada' => '45-60 minutos',
				'es_urgencia'      => false,
				'icono_slug'       => 'service-domicilio',
				'ilustracion_slug' => 'hero-home',
				'cta_texto'        => 'Agendar visita',
				'incluye' => array(
					array( 'item' => 'Consultas generales' ),
					array( 'item' => 'Vacunación' ),
					array( 'item' => 'Controles postoperatorios' ),
					array( 'item' => 'Curaciones simples' ),
					array( 'item' => 'Toma de muestras básicas' ),
					array( 'item' => 'Evaluación geriátrica' ),
				),
				'casos_frecuentes' => array(),
			),
		),
		array(
			'slug'  => 'medicina-preventiva',
			'title' => 'Medicina preventiva y vacunas',
			'excerpt' => 'Planes preventivos según edad, especie y estilo de vida. Calendario de vacunas, desparasitación, chequeos y control de peso.',
			'content' => "<p>La prevención es uno de nuestros ejes más fuertes. Desarrollamos planes preventivos según edad, especie, estilo de vida y antecedentes clínicos para anticiparnos a los problemas.</p>",
			'cat'   => 'preventivo',
			'order' => 12,
			'fields' => array(
				'precio_desde'     => 28000,
				'duracion_estimada' => '30 minutos',
				'es_urgencia'      => false,
				'icono_slug'       => 'service-preventiva',
				'ilustracion_slug' => 'hero-cachorro',
				'cta_texto'        => 'Agendar control',
				'incluye' => array(
					array( 'item' => 'Calendario de vacunas' ),
					array( 'item' => 'Desparasitación interna y externa' ),
					array( 'item' => 'Chequeos preventivos' ),
					array( 'item' => 'Control de peso' ),
					array( 'item' => 'Planes para cachorros y senior' ),
					array( 'item' => 'Recomendaciones nutricionales' ),
				),
				'casos_frecuentes' => array(),
			),
		),
	);

	foreach ( $servicios as $s ) {
		$existing = get_page_by_path( $s['slug'], OBJECT, 'servicio' );
		if ( $existing ) {
			continue;
		}
		$id = wp_insert_post( array(
			'post_type'    => 'servicio',
			'post_status'  => 'publish',
			'post_name'    => $s['slug'],
			'post_title'   => $s['title'],
			'post_excerpt' => $s['excerpt'],
			'post_content' => $s['content'],
			'menu_order'   => $s['order'],
		) );
		if ( ! is_wp_error( $id ) && $id ) {
			perrito_seed_fields( $id, $s['fields'] );
			wp_set_object_terms( $id, array( $s['cat'] ), 'servicio_categoria' );
		}
	}
}
